add our friends
ArtemHryn/petly_frontend pull request #7
Opened 2023-02-15 22:12 UTC by Alexandr1899

разметка и стилизация моб/табл/деск (пока без данных)

2023-02-15 23:05 UTC, ArtemHryn requested changes

2023-02-15 23:05 UTC, ArtemHryn commented on src/components/App.jsx
> -          <Route path="our_friend" element={<OurFriend />} />
ми не змінюємо не свої файли

2023-02-15 23:05 UTC, ArtemHryn commented on src/components/SharedLayout/SharedLayout.jsx
> -      <Suspense fullback={null}>
тут також не зміюємо

2023-02-15 23:05 UTC, ArtemHryn commented on src/pages/OurFriend.jsx
> +                        <FriendsMainLink>title</FriendsMainLink>
є окремий компонент, який називається Title, не створюємо однакові компоненти

2023-02-16 22:15 UTC, Alexandr1899 commented on src/components/App.jsx
> -          <Route path="our_friend" element={<OurFriend />} />
+

2023-02-16 22:15 UTC, Alexandr1899 commented on src/components/SharedLayout/SharedLayout.jsx
> -      <Suspense fullback={null}>
+

2023-02-16 22:15 UTC, Alexandr1899 commented on src/pages/OurFriend.jsx
> +                        <FriendsMainLink>title</FriendsMainLink>
добавил Title

2023-02-16 22:26 UTC, ArtemHryn approved these changes

2023-02-16 22:26 UTC, merged