User page
ArtemHryn/petly_frontend pull request #9
Opened 2023-02-15 23:15 UTC by Kseniia30

2023-02-15 23:16 UTC, ArtemHryn commented on src/components/SharedLayout/SharedLayout.jsx
> -      <Suspense fullback={null}>
не потрібно змінювати не свої файли

2023-02-15 23:18 UTC, Kseniia30 commented on src/components/SharedLayout/SharedLayout.jsx
> -      <Suspense fullback={null}>
забула прибрати

2023-02-15 23:23 UTC, ArtemHryn requested changes

2023-02-15 23:23 UTC, ArtemHryn commented on src/pages/Profile.jsx
> +import { MdPhotoCamera } from 'react-icons/md';
розбий файл на компоненти, він же величезний

2023-02-15 23:23 UTC, ArtemHryn commented on src/pages/Profile.jsx
> +export const UserModalFirst = () => {
1. Що модалка робить в 1 файлі з компонентом
2. Модалки пише Богдан

2023-02-15 23:23 UTC, ArtemHryn commented on src/pages/Profile.jsx
> +                    <UserInfoTable>
це не таблиця, а звичайний список, де кожна li має 3 елементи, деякі огорни в дів щоб вирівнювати, також є компонент Box для огортання

2023-02-16 18:39 UTC, Kseniia30 commented on src/pages/Profile.jsx
> +export const UserModalFirst = () => {
прибрала

2023-02-16 19:56 UTC, Kseniia30 commented on src/pages/Profile.jsx
> +                    <UserInfoTable>
переробила

2023-02-17 14:09 UTC, ArtemHryn approved these changes

2023-02-17 14:10 UTC, merged